site_name: Postgres Operator
repo_url: https://github.com/zalando/postgres-operator
theme: readthedocs

nav:
  - 概念: 'index.md'
  - 快速上手: 'quickstart.md'
  - Postgres Operator UI: 'operator-ui.md'
  - 管理员指南: 'administrator.md'
  - 用户指南: 'user.md'
  - 开发者指南: 'developer.md'
  - 参考资料:
    - Operator 参数: 'reference/operator_parameters.md'
    - 清单参数: 'reference/cluster_manifest.md'
    - 命令行参数和环境变量: 'reference/command_line_and_environment.md'
  - Google Summer of Code 2019: 'gsoc-2019/ideas.md'
